Remove load average "normalization", only confusing to users
Most users expect the value to be monitored to at least be somewhat
related to what `top` and `w` show.  While reading up on the subject
I've decided to remove this oddity for v3.0.  Users will have to tune
this anyway to suit their systems.

However, I'm keeping Christian Lockley's 1 + 5 min average, since that
smoothes out any rapid increases, and I'm also keeping the new 5 mins
exception: peak loads within the first 5 mins of uptime are ignored.

Signed-off-by: Joachim Nilsson <troglobit@gmail.com>